Source/eCOMM/eCOMM/Models/Person/PersonModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace eCOMM.Models.Person
{
    public class PersonModel
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName{ get; set; }

        [DisplayName("Age")]
        public int Age { get; set; }

        [DisplayName("Created By")]
        public string CreatedBy { get; set; }

        [DisplayName("Created Date")]
        public DateTime CreatedDate { get; set; }

        public string ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}

Source/eCOMM/eCOMM/Models/Person/PersonSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCOMM.Models.Person
{
    public class PersonSearchModel
    {

    }
}

Source/eCOMM/eCOMM/Controllers/PersonController.cs
using eCOMM.Models;
using eCOMM.Models.Person;
using eCOMM.Repositories;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCOMM.Controllers
{
    public class PersonController : Controller
    {
        private readonly PersonRepository _personRepository;

        public PersonController()
        {
            string connStr = ConfigurationManager.ConnectionStrings["eCOMMConnection"].ToString();
            _personRepository = new PersonRepository(connStr);
        }

        //
        // GET: /Person/
        public ActionResult Index()
        {
            var model = _personRepository.GetPersonList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PersonModel person)
        {
            if (ModelState.IsValid)
            {
                person.CreatedBy = "dummyUser";
                person.CreatedDate = DateTime.Now;
                _personRepository.CreatePerson(person);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }

        public ActionResult Edit(int id)
        {
            var person = _personRepository.GetPersonById(id);
            return View(person);
        }

        [HttpPost]
        public ActionResult Edit(PersonModel person)
        {
            if (ModelState.IsValid)
            {
                person.ModifiedBy = "dummyModifier";
                person.ModifiedDate = DateTime.Now;
                _personRepository.UpdatePerson(person);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Edit", new { id = person.Id });
        }

        public ActionResult Detail(int id)
        {
            var person = _personRepository.GetPersonById(id);
            return View(person);
        }

        public ActionResult Delete(int id)
        {
            _personRepository.DeletePerson(id);
            return RedirectToAction("Index");
        }
	}
}

Source/eCOMM/eCOMM/Views/Person/Create.cshtml
@model eCOMM.Models.Person.PersonModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Person</h2>

@using (Html.BeginForm("Create", "Person", FormMethod.Post, new {id = "createForm", enctype="multipart/form-data"}))
{
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName)
        @Html.TextBoxFor(model => model.FirstName, new { @class ="form-control", placeholder = "First Name" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LastName)
        @Html.TextBoxFor(model => model.LastName, new { @class ="form-control", placeholder = "Last Name" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Age)
        @Html.TextBoxFor(model => model.Age, new { @class ="form-control", placeholder = "Age" })
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    @Html.ActionLink("Cancel", "Index", "Person", new { @class ="btn btn-primary"})
}

Source/eCOMM/eCOMM/Views/Person/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

Source/eCOMM/eCOMM/Views/Person/Detail.cshtml
@model eCOMM.Models.Person.PersonModel
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Person Detail</h2>
<form>
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName)
        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", disabled="disabled"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LastName)
        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", disabled="disabled"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Age)
        @Html.TextBoxFor(model => model.Age, new { @class = "form-control", disabled="disabled"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CreatedBy)
        @Html.TextBoxFor(model => model.CreatedBy, new { @class = "form-control", disabled="disabled"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CreatedDate)
        @Html.TextBoxFor(model => model.CreatedDate, new { @class = "form-control", disabled="disabled"}) 
    </div>
</form>

Source/eCOMM/eCOMM/Views/Person/Edit.cshtml
@model eCOMM.Models.Person.PersonModel
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update Person</h2>

@using (Html.BeginForm("Edit", "Person", FormMethod.Post, new {id = "createForm", enctype="multipart/form-data"}))
{
    @Html.HiddenFor(model=>model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName)
        @Html.TextBoxFor(model => model.FirstName, new { @class ="form-control", placeholder = "First Name" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LastName)
        @Html.TextBoxFor(model => model.LastName, new { @class ="form-control", placeholder = "Last Name" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Age)
        @Html.TextBoxFor(model => model.Age, new { @class ="form-control", placeholder = "Age" })
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "Index", "Person", new { @class ="btn btn-primary"})
}

Source/eCOMM/eCOMM/Views/Person/Index.cshtml
@model IEnumerable<eCOMM.Models.Person.PersonModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
  <h2>Person List</h2>
  @Html.ActionLink("Create Person", "Create", "Person", new { @class ="btn btn-primary"})
  <table class="table">
    <thead>
      <tr>
        <th>Person Id</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Age</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var person in Model)
      { 
        <tr>
            <td>@Html.ActionLink(@person.Id.ToString(), "Detail", "Person", new {id = @person.Id}, null)</td>
            <td>@person.FirstName</td>
            <td>@person.LastName</td>
            <td>@person.Age</td>
            <td>@Html.ActionLink("edit", "Edit", "Person", new {id = @person.Id}, null)</td>
            <td>@Html.ActionLink("delete", "Delete", "Person", new {id = @person.Id}, null)</td>
        </tr>
      }
    </tbody>
  </table>
</div>